sonar.projectKey=mrlachir_test-sonar
sonar.organization=mrlachir
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.binaries=build/classes/java/main
sonar.host.url=https://sonarcloud.io
sonar.token=1a3dfa4f47f78fbf3d8e2cb91be915e581bdad64
sonar.sourceEncoding=UTF-8