spring.application.name=backend
#encryption.secret=${ENCRYPTION_SECRET:68PSkgdEw7rWU+bvGi/BVOhR9NiId8rgawn5iCw+TSU=}
encryption.secret=MySuperSecretKey

spring.datasource.url=jdbc:mysql://localhost:3306/smartmaildb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=smartmail_user
spring.datasource.password=smartmail_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true